#!/bin/bash
set -euo pipefail
set -x

# Startup:
# brctl addbr br0
# ip link set br0 up

ip netns add netns${1}
ip netns exec netns${1} ip link set dev lo up

ip link add veth${1}a type veth peer name veth${1}b
ip link set veth${1}a up
ip link set veth${1}b netns netns${1}

# Showing the IPs are assigned:
#ip netns exec netns${1} ifconfig -a

ip netns exec netns${1} ip addr add 10.0.0.${1}/24 dev veth${1}b
ip netns exec netns${1} ip link set veth${1}b up

brctl addif br0 veth${1}a

# Playing around:
# ip netns exec netns1 ping 10.0.0.2
# ip netns exec netns{1,2} arp
