# Golang 1.9.2 with 'net/http' from stdlib
FROM golang:1.9.2

ADD .gen/httpserver scripts/dnsgames_init /
ADD golang-http/main.go /

RUN go build /main.go && mv main /

ENTRYPOINT ["/dnsgames_init"]
CMD ["/main"]
