# Python 3.6.3 with Tornado 4.5.2
FROM python:3.6.3

RUN pip install tornado==4.5.2

ADD .gen/httpserver scripts/dnsgames_init /
ADD python3-tornado/main.py /

ENTRYPOINT ["/dnsgames_init"]
CMD ["/main.py"]
